# Generated by Django 2.1.3 on 2018-11-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181125_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nikename',
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=20, verbose_name='昵称'),
        ),
    ]
